[package]
name = "pot"
version = "0.1.0-alpha.3"
edition = "2021"
description = "A concise binary serialization format written for `BonsaiDb`."
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/khonsulabs/pot"
keywords = ["serialization", "serde"]
categories = ["encoding"]

[features]
default = []

[dependencies]
serde = "1"
thiserror = "1"
tracing = { version = "0.1", features = [
    "release_max_level_off",
], optional = true }
byteorder = "1"
bytes = "1"
half = "1"
derive-where = "1.0.0-rc.1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
rand = "0.8"
fake = "2"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
cli-table = "0.4"
thousands = "0.2"
ciborium = "0.2"
bincode = "1"
criterion = { version = "0.3", features = ["html_reports"] }
serde_bytes = "0.11"
serde_json = "1"

[[bench]]
name = "benchmarks"
harness = false
