name: Benchmarks

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build benchmarks
        run: |
          cargo bench --no-run

      - name: Run benchmarks
        run: |
          cargo bench -p benchmarks -- -s0

      - name: Make plots have a solid white background
        run: |
          find target/criterion -name "*.svg" -exec sed -i 's/<svg/<svg style="background-color:#EEE;"/g' {} \;

      - name: Deploy Docs
        if: ${{ github.ref == 'refs/heads/main'  }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/criterion/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /benchmarks/
          clean: true
