name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy
        run: |
          cargo clippy

      - name: Run unit tests (Pot)
        run: |
          cargo test -p pot

      - name: Run unit tests (Workspace)
        run: |
          cargo test --all-features
